//! tinted-boot's AArch64 machine bring-up and Patina DXE handoff.
//!
//! The reset stage runs on QEMU's `virt` machine, sets up RAM, translation,
//! console, interrupts and the device tree, then loads Patina's DXE core from
//! the firmware volume in flash. Patina publishes the UEFI services and platform
//! tables and installs the volume's FV protocols from the handoff HOB.
//!
//! Bring-up order matters: the reset trampoline copies the ELF and FV to RAM;
//! the entry sets a stack and exception vectors; the MMU gives RAM Normal memory
//! attributes instead of reset's Device-nGnRnE; then the console and HOB list
//! can be built before Patina starts.

#![no_std]
#![no_main]

extern crate alloc;

mod allocator;
mod arch;
mod block;
mod boot;
mod console;
mod drivers;
mod fat;
mod fdt;
mod fs;
mod hob;
mod loader;
mod storage;
mod uefi;

/// Link-time addresses, generated by `build.rs`. The firmware's image base, its
/// stack top, and its heap window live there because mold reads no linker
/// scripts: there are no symbols to ask.
mod layout {
    include!(concat!(env!("OUT_DIR"), "/layout.rs"));
}

mod platform;

use core::panic::PanicInfo;

/// Where the DXE core's image is loaded. It is memory the core is offered as
/// system memory: an image in memory the core has never heard of is an image it
/// cannot map, and it stops with "DXE Core not mapped in GCD".
const DXE_CORE_LOAD_ADDR: usize = 0x4400_0000;

/// The machine's device windows: everything this firmware and the core reach
/// through an address rather than through RAM. Their sizes are the ones the
/// machine's own description gives them.
fn machine_devices() -> [(usize, usize); 9] {
    [
        (
            platform::FLASH_BASE,
            platform::FLASH_BASE + platform::FLASH_SIZE,
        ),
        (platform::GIC_DIST_BASE, platform::GIC_DIST_BASE + 0x1_0000),
        (
            platform::GIC_REDIST_BASE,
            platform::GIC_REDIST_BASE + platform::GIC_REDIST_SIZE,
        ),
        (platform::UART0_BASE, platform::UART0_BASE + 0x1000),
        (platform::RTC_BASE, platform::RTC_BASE + 0x1000),
        (platform::FW_CFG_BASE, platform::FW_CFG_BASE + 0x1000),
        (
            platform::VIRTIO_MMIO_BASE,
            platform::VIRTIO_MMIO_BASE + platform::VIRTIO_MMIO_SIZE * platform::VIRTIO_MMIO_COUNT,
        ),
        (
            platform::PCIE_ECAM_BASE,
            platform::PCIE_ECAM_BASE + platform::PCIE_ECAM_SIZE,
        ),
        (
            platform::PCIE_MMIO32_BASE,
            platform::PCIE_MMIO32_BASE + platform::PCIE_MMIO32_SIZE,
        ),
    ]
}

/// How wide the machine's physical addresses are. The MMU is programmed with the
/// same width, and the DXE core sizes its address spaces from it.
const PHYSICAL_ADDRESS_BITS: u8 = 40;

/// The firmware's Rust entry. `_start` has set the stack and enabled FP/SIMD;
/// `boot_args` is the machine description the boot protocol passed in `x0`.
///
/// # Safety
///
/// Called only from the reset vector, at the configured exception level.
#[unsafe(no_mangle)]
pub unsafe extern "C" fn rust_start(
    boot_args: usize,
    volume_address: usize,
    volume_size: usize,
) -> ! {
    arch::vectors::install();
    match arch::current_el() {
        2 => {
            // SAFETY: this is the only EL2 entry, and nothing at EL1 exists yet.
            unsafe { arch::drop_to_el1() }
        }
        1 => rust_el1_main(boot_args, volume_address, volume_size),
        level => {
            console::emergency_write(
                "\r\n[tinted-boot] fault: entered at an exception level tinted-boot does not handle\r\n",
            );
            let _ = level;
            arch::halt()
        }
    }
}

/// EL1 bring-up. Entered either from the reset vector or, after the EL2 drop,
/// from `el1_entry`.
#[unsafe(no_mangle)]
pub extern "C" fn rust_el1_main(boot_args: usize, volume_address: usize, volume_size: usize) -> ! {
    // SAFETY: the heap window is RAM the firmware reserves in the memory map
    // (see `mem`), and this runs once, before anything allocates - it is the
    // page tables' source of memory.
    unsafe { allocator::init(layout::HEAP_BASE as *mut u8, layout::HEAP_SIZE) };

    // The map covers the whole RAM window the machine can have; the device tree
    // narrows what the firmware reports to the OS further down.
    arch::mmu::init(platform::RAM_BASE + platform::RAM_SIZE_MAX);

    console::init();
    println!("\r\ntinted-boot UEFI firmware (AArch64)");
    println!(
        "[tinted-boot] EL{} | counter at {} Hz | heap {} KiB free",
        arch::current_el(),
        arch::timer::frequency(),
        allocator::free_bytes() / 1024
    );

    println!("[tinted-boot] boot argument: {boot_args:#x}");
    let mut device_tree = 0..0;
    match fdt::Fdt::new(boot_args) {
        Some(tree) => {
            println!(
                "[tinted-boot] device tree at {:#x} ({} bytes)",
                boot_args, tree.total_size
            );
            device_tree = boot_args..boot_args + tree.total_size;
            if let Some((base, size)) = tree.memory() {
                println!("[tinted-boot] memory: {:#x}..{:#x}", base, base + size);
                platform::set_ram_end((base + size) as usize);
            } else {
                println!("[tinted-boot] the tree declares no memory node; using the built-in size");
            }
        }
        None => {
            println!(
                "[tinted-boot] no device tree handed over; using the built-in platform description"
            )
        }
    }
    println!(
        "[tinted-boot] RAM published to the OS: {:#x}..{:#x}",
        platform::RAM_BASE,
        platform::ram_end()
    );

    // Leave the machine with a tick. The core brings its own interrupt
    // controller up, but it sleeps for an interrupt when it waits for one, and a
    // timer that nothing arms is a core that stops. Interrupts stay masked: the
    // core unmasks them when it is ready.
    arch::gicv3::init();
    arch::timer::arm(arch::timer::period_ticks());
    println!(
        "[tinted-boot] timer armed at {} Hz; interrupts stay masked until the core wants them",
        arch::timer::frequency()
    );

    // The reset code copied the firmware volume to RAM while translation was
    // off. Patina's FFS reader validates the FV and its DXE-core FFS file; the
    // PE loader then relocates the PE32 section into executable system memory.
    // The volume itself survives the handoff for Patina's FV dispatcher.
    // SAFETY: the reset code copied this many bytes to this address, and no
    // firmware allocation or device tree buffer overlaps the volume.
    let volume = unsafe { core::slice::from_raw_parts(volume_address as *const u8, volume_size) };
    let core_bytes = match dxe_core_from_volume(volume) {
        Ok(bytes) => bytes,
        Err(error) => {
            println!("[tinted-boot] DXE firmware volume is invalid: {error}");
            arch::halt()
        }
    };
    // Patina maps its own image by the allocation HOB, so it must live in
    // system memory rather than in the firmware's reserved windows.
    let core = match loader::pe::load_at(core_bytes, DXE_CORE_LOAD_ADDR) {
        Ok(core) => core,
        Err(error) => {
            println!("[tinted-boot] the DXE core image could not be loaded: {error:?}");
            arch::halt()
        }
    };
    println!(
        "[tinted-boot] DXE core loaded at {:#x} ({:#x} bytes), entry {:#x}",
        core.base, core.size, core.entry
    );

    // The machine is up, so what is left is to describe it and hand over. The
    // core provides the UEFI services and, through the components the platform
    // crate gives it, this machine's tables and drivers.
    let reserved = [
        // The image, the stack above it, the page pool the core's own image was
        // loaded from, and the heap: this firmware's memory, which the core must
        // not allocate. The stack is the one that matters most: the core runs on
        // it from the first instruction.
        (platform::RAM_BASE, layout::HEAP_BASE + layout::HEAP_SIZE),
        // The device tree, read in place from the address the boot stage left it
        // at, which the core hands on to the operating system.
        (device_tree.start, device_tree.end),
        // The dispatcher reads the FV after handoff, so it cannot be reclaimed
        // along with the rest of the RAM that the DXE core may allocate.
        (volume_address, volume_address + volume_size),
    ];
    // Memory the core may build its own bookkeeping in before its allocator
    // exists. It is the first of the memory offered as system memory, because the
    // core takes the attributes it initializes its memory space with from the
    // resource descriptor that covers this window. Its size is the core's: the
    // region is the backing store for the memory blocks it records that space
    // in, and it refuses a window smaller than one slice of them.
    let core_memory = (
        layout::HEAP_BASE + layout::HEAP_SIZE,
        layout::HEAP_BASE + layout::HEAP_SIZE + 0x180_0000,
    );
    debug_assert!(DXE_CORE_LOAD_ADDR > core_memory.1);
    let devices = machine_devices();
    // SAFETY: bring-up is complete and this is the only HOB list built.
    let hob_list = unsafe {
        hob::build(
            (platform::RAM_BASE, platform::ram_end()),
            &reserved,
            core_memory,
            // The width this firmware programmed its translation for, which is
            // the machine's: 40 bits is what the MMU was told to use.
            PHYSICAL_ADDRESS_BITS,
            (core.base, core.size, core.entry),
            (volume_address, volume_size),
            // This firmware's stack, which the core runs on from the first
            // instruction: it is below the stack pointer and it is all the room
            // the firmware and the core have together.
            (layout::STACK_TOP - 0x1_0000, 0x1_0000),
            // The machine's devices, as this firmware maps them itself: the
            // console, the interrupt controller, the serial and virtual I/O
            // windows, and PCIe's configuration and memory windows.
            &devices,
        )
    };
    println!(
        "[tinted-boot] HOB list at {:#x}; handing over to the DXE core",
        hob_list as usize
    );

    // SAFETY: the machine is in its final state, the HOB list describes the
    // memory the core may use and the image it is running from, and nothing else
    // is running. The core does not return.
    let entry: unsafe extern "efiapi" fn(*const core::ffi::c_void) -> ! =
        unsafe { core::mem::transmute(core.entry) };
    unsafe { entry(hob_list as *const core::ffi::c_void) }
}

/// Finds the DXE core PE32 section inside a PI firmware volume. Patina parses
/// the FV and FFS headers; borrowing the section payload avoids copying the
/// entire DXE image just to inspect its four-byte section header.
fn dxe_core_from_volume(bytes: &[u8]) -> Result<&[u8], &'static str> {
    let volume = patina_ffs::volume::VolumeRef::new(bytes).map_err(|_| "invalid FV header")?;
    for file in volume.files() {
        let file = file.map_err(|_| "invalid FFS file")?;
        if file.name() != patina::guid::DXE_CORE_ID {
            continue;
        }
        if file.file_type_raw() != 0x05 {
            return Err("DXE core GUID has the wrong FFS file type");
        }
        let section = file.content();
        if section.len() < 4 || section[3] != 0x10 {
            return Err("DXE core has no PE32 section");
        }
        let size = section[0] as usize | (section[1] as usize) << 8 | (section[2] as usize) << 16;
        if size < 4 || size == 0xff_ffff {
            return Err("invalid DXE core section size");
        }
        // FileRef's content is a subslice of `bytes`; express the result
        // against that original borrow, rather than the temporary FileRef.
        let offset = section.as_ptr() as usize - bytes.as_ptr() as usize;
        return bytes
            .get(offset + 4..offset + size)
            .ok_or("truncated DXE core section");
    }
    Err("DXE core FFS file not found")
}

#[panic_handler]
fn panic(info: &PanicInfo) -> ! {
    // Before the console is up, formatting is not safe: the MMU may still be
    // off, and formatting reads tables it did not align.
    if console::ready() {
        println!("\r\n[tinted-boot] panic: {info}");
    } else {
        console::emergency_write("\r\n[tinted-boot] panic before console bring-up\r\n");
    }
    arch::halt()
}
