//! Entry, exception-level bring-up, and the exception vectors.
//!
//! The reset trampoline (`boot/boot.S.in`, generated by `tools/mkimage`) copies
//! the firmware and its PI firmware volume out of flash. It clears the
//! zero-initialised region and leaves the core at QEMU's reset exception level:
//! EL1 by default, EL2 with `virtualization=on`. The UEFI
//! specification puts the boot loader and the operating system at EL1, so an
//! EL2 reset drops a level first.
//!
//! Order matters here: a stack and FP/SIMD before the first compiler-generated
//! instruction, then the vectors so a fault reports, then Normal memory via the
//! MMU. Until translation is on every address is Device-nGnRnE, where an
//! unaligned access faults, so nothing before `mmu::init` may read a table it
//! did not align.

use core::arch::global_asm;

pub mod gic;
pub mod gicv3;
pub mod mmu;
pub mod psci;
pub mod timer;
pub mod vectors;

global_asm!(
    r#"
.section .text.boot, "ax"
.global _start
_start:
    // Nothing may interrupt bring-up: an IRQ here has no vector table to land in.
    msr     daifset, #0xf

    // The reset code's arguments - device tree and FV's RAM base and size -
    // go into callee-saved registers: register setup clobbers the caller-saved
    // ones, and the EL2 drop changes exception levels through an `eret`.
    mov     x19, x0
    mov     x20, x1
    mov     x21, x2

    ldr     x2, ={STACK_TOP}
    mov     sp, x2

    // FP/SIMD is off at reset and Rust's code generation uses NEON for bulk
    // copies, so it has to be on before the first compiler-generated
    // instruction. CPTR_EL2 only exists at EL2.
    mrs     x3, CurrentEL
    cmp     x3, #(2 << 2)
    b.ne    1f
    msr     cptr_el2, xzr
1:
    mov     x3, #(3 << 20)
    msr     cpacr_el1, x3
    isb

    // SCTLR_EL1.A makes every data access check its alignment, and an earlier
    // stage may have left it set. Compiled code does not align everything it
    // reads, so it stays off. SA and SA0 stay as they are: a misaligned stack
    // pointer is a real bug and should still fault.
    mrs     x3, sctlr_el1
    bic     x3, x3, #(1 << 1)
    msr     sctlr_el1, x3
    isb

    // Translation, before the first compiled instruction that touches memory.
    // With the MMU off every address is Device-nGnRnE, and Device memory has
    // rules compiled code breaks without meaning to: the atomic read-modify-
    // write the global allocator's first lock performs is unpredictable there,
    // as are `dc zva` and unaligned multi-register accesses. A core that reports
    // those as faults stops bring-up at the heap; a core that does not hides the
    // mistake until the firmware runs on one that does.
    //
    // The table is read-only data in the image - no allocation, no writes to set
    // it up - and covers the two 1 GiB blocks the firmware runs in: the low one
    // Device, so the flash and the console an early panic writes to are
    // reachable, and the one above it RAM. `mmu::init` replaces it with the full
    // map once Rust is running and can allocate.
    ldr     x2, ={BOOT_TABLE}
    msr     ttbr0_el1, x2
    ldr     x3, ={MAIR}
    msr     mair_el1, x3
    ldr     x3, ={TCR}
    msr     tcr_el1, x3
    dsb     ish
    isb
    mrs     x3, sctlr_el1
    orr     x3, x3, #1
    msr     sctlr_el1, x3
    isb
    /* x19-x21 carry the boot arguments through. */
    mov     x0, x19
    mov     x1, x20
    mov     x2, x21
    b       rust_start
"#,
    STACK_TOP = const crate::layout::STACK_TOP,
    BOOT_TABLE = sym crate::arch::mmu::BOOT_TABLE,
    MAIR = const crate::arch::mmu::MAIR,
    TCR = const crate::arch::mmu::TCR,
);

global_asm!(
    r#"
.global el1_entry
el1_entry:
    // Reached from EL2 through ELR_EL2, where SP_EL1 has been selected but
    // never set, so the stack is loaded here before any Rust code runs. x19
    // still holds the boot stage's device tree.
    ldr     x2, ={STACK_TOP}
    mov     sp, x2
    mov     x0, x19
    mov     x1, x20
    mov     x2, x21
    b       rust_el1_main
"#,
    STACK_TOP = const crate::layout::STACK_TOP,
);

/// The current exception level, 0 to 3.
pub fn current_el() -> u8 {
    let el: u64;
    // SAFETY: reading CurrentEL has no side effects.
    unsafe {
        core::arch::asm!("mrs {}, CurrentEL", out(reg) el, options(nomem, nostack, preserves_flags))
    };
    ((el >> 2) & 0b11) as u8
}

/// Drops from EL2 to EL1 and continues at `el1_entry`. Never returns. It
/// does not touch `x19-x21`, so the boot arguments survive the drop.
///
/// The reset state at EL2 is not a state EL1 can be entered from: HCR_EL2 must
/// stop trapping the physical timer and the counter, CNTHCTL_EL2 must let EL1
/// see them, and the EL1 entry must be AArch64 with DAIF masked.
///
/// # Safety
///
/// Only callable from EL2, and only before any EL1 state exists.
pub unsafe fn drop_to_el1() -> ! {
    // SAFETY: the caller is at EL2, where these registers exist.
    unsafe {
        core::arch::asm!(
            "msr     cptr_el2, xzr", // no EL2 traps for FP/SIMD
            "mov     x0, #(3 << 20)",
            "msr     cpacr_el1, x0", // FP/SIMD usable at EL1
            "mov     x0, #3",        // CNTHCTL_EL2: EL1PCTEN | EL1PCEN
            "msr     cnthctl_el2, x0",
            "msr     cntvoff_el2, xzr", // virtual counter matches the physical one
            "mrs     x0, hcr_el2",
            "orr     x0, x0, #(1 << 31)", // RW: EL1 is AArch64
            "bic     x0, x0, #((1 << 4) | (1 << 3) | (1 << 5))", // no IRQ/FIQ/SError routing to EL2
            "msr     hcr_el2, x0",
            "adrp    x0, el1_entry",
            "add     x0, x0, :lo12:el1_entry",
            "msr     elr_el2, x0",
            "mov     x0, #0x3c5", // EL1h with DAIF masked
            "msr     spsr_el2, x0",
            "isb",
            "eret",
            options(noreturn)
        )
    }
}

/// Parks the core with interrupts masked. Used by the panic path and by a clean
/// shutdown that has nothing left to do.
pub fn halt() -> ! {
    loop {
        // SAFETY: `wfe` only waits for an event; with interrupts masked it parks
        // the core until one arrives.
        unsafe { core::arch::asm!("wfe", options(nomem, nostack)) }
    }
}
