// The firmware links as a RAM image: mold places it at `LOAD_ADDR` with entry
// `_start`. QEMU's reset-vector trampoline copies it out of flash, along with
// the PI firmware volume holding the DXE core. mold cannot read linker scripts
// (it rejects `SECTIONS` and `ENTRY` outright), so everything a script would
// normally express - image base, entry, stack and heap addresses - is a
// constant here, handed to rustc and the firmware through `layout.rs`.

use std::path::PathBuf;

/// Where the firmware runs. RAM starts at 0x4000_0000 on QEMU's `virt`; the
/// image sits 512 KiB above it, above anything a boot stage might leave behind.
const LOAD_ADDR: u64 = 0x4008_0000;

/// The stack top. The firmware's image is far smaller than the gap between the
/// image base and this address, so the stack has room without a linker script
/// having to say where `.bss` ends.
const STACK_TOP: u64 = 0x4020_0000;

/// The Rust heap, and the page pool's window, both reserved by the memory map.
pub const HEAP_BASE: u64 = 0x4100_0000;
pub const HEAP_SIZE: u64 = 0x0100_0000;

fn main() {
    let out = PathBuf::from(std::env::var("OUT_DIR").unwrap());
    let layout = out.join("layout.rs");
    std::fs::write(
        &layout,
        format!(
            "// Generated by build.rs: the firmware's link-time layout.\n\
             pub const LOAD_ADDR: usize = {LOAD_ADDR:#x};\n\
             pub const STACK_TOP: usize = {STACK_TOP:#x};\n\
             pub const HEAP_BASE: usize = {HEAP_BASE:#x};\n\
             pub const HEAP_SIZE: usize = {HEAP_SIZE:#x};\n"
        ),
    )
    .unwrap();
    println!("cargo:rerun-if-changed=build.rs");

    println!("cargo:rustc-link-arg=--image-base={LOAD_ADDR:#x}");
    println!("cargo:rustc-link-arg=--entry=_start");
    println!("cargo:rustc-link-arg=--gc-sections");
}
